backend:
  image: "public.ecr.aws/your-alias/todo-backend:latest"
  replicas: 2
  port: 4000

frontend:
  image: "public.ecr.aws/your-alias/todo-frontend:latest"
  replicas: 2
  port: 3000
  backend_url: "http://todo-backend-service:4000"
