apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tkwk5445/devops_todo_manifest.git
    targetRevision: main
    path: frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
