apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-backend
  ports:
  - protocol: TCP
    port: {{ .Values.backend.port }}
    targetPort: {{ .Values.backend.port }}
  type: ClusterIP
