apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: Opaque
data:
  access_key: {{ .Values.secrets.aws_access_key }}
  secret_key: {{ .Values.secrets.aws_secret_key }}

---

apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  jwt_secret: {{ .Values.secrets.jwt_secret }}
